version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Deploy
          command: vercel deploy --prod --token=$VERCEL_TOKEN 

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main