version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      # - run:
      #     name: Run Tests
      #     command: sudo npm test #change test in package.json 
      - run:
          name: Hello World!
          command: echo "Hello, World!"

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Deploy
          command: vercel deploy --prod --token=$VERCEL_TOKEN 

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
